github.com:
    users:
        MIKK0Z:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: MIKK0Z
