[general]
import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[window]
padding.x = 8
padding.y = 8
decorations = "None"
opacity = 0.6

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 14

[mouse]
hide_when_typing = true

[cursor]
style.shape = "Beam"

