import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[window]
padding.x = 8
padding.y = 8
decorations = "None"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12

[cursor]
style.shape = "Beam"

[mouse]
hide_when_typing = true